/*
 All the levels should be in order. Otherwise there will be errors
 */
module.exports.levels=[
	{
		level:1,
		name:'Basic objects',
		slug:'basic_objects',
		description:'Learn basic terms in money management',
		steps:[
			{
				name:'Intro',
				slug:'intro',
			},
			{
				name:'Accounts',
				slug:'account',
			},
			{
				name:'Transactions',
				slug:'transaction',
			},
			{
				name:'Categories',
				slug:'category',
			},
			{
				name:'Tags',
				slug:'tag',
			},
			{
				name:'Snapshots',
				slug:'snapshot',
			},
			{
				name:'Organisations',
				slug:'organisation',
			},
		]
	},
	{
		level:2,
		name:'Data extraction',
		slug:'data_extraction',
		description:'Extract info from emails and bank statements',
		steps:[
			{
				name:'Intro',
				slug:'intro',
			},
			{
				name:'Document parsing',
				slug:'doc_parsing',
			},
			{
				name:'Transactions',
				slug:'transactions',
			},
			{
				name:'Categories',
				slug:'categories',
			},
			{
				name:'Tags',
				slug:'tags',
			},
			{
				name:'Snapshots',
				slug:'snapshots',
			},
			{
				name:'Organisations',
				slug:'organisations',
			},
		]
	},
	{
		level:3,
		name:'Automation',
		slug:'automation',
		description:'Reduce manual work',
		steps:[
			{
				name:'Intro',
				slug:'intro',
			},
			{
				name:'Accounts',
				slug:'accounts',
			},
			{
				name:'Transactions',
				slug:'transactions',
			},
			{
				name:'Categories',
				slug:'categories',
			},
			{
				name:'Tags',
				slug:'tags',
			},
			{
				name:'Snapshots',
				slug:'snapshots',
			},
			{
				name:'Organisations',
				slug:'organisations',
			},
		]
	},
	{
		level:4,
		name:'Advanced objects',
		slug:'advanced_objects',
		description:'Learn advanced concepts in money management',
		steps:[
			{
				name:'Intro',
				slug:'intro',
			},
			{
				name:'Accounts',
				slug:'accounts',
			},
			{
				name:'Transactions',
				slug:'transactions',
			},
			{
				name:'Categories',
				slug:'categories',
			},
			{
				name:'Tags',
				slug:'tags',
			},
			{
				name:'Snapshots',
				slug:'snapshots',
			},
			{
				name:'Organisations',
				slug:'organisations',
			},
		]
	},
	{
		level:5,
		name:'Data quality',
		slug:'data_quality',
		description:'Maintaining quality and confidence in your data',
		steps:[
			{
				name:'Intro',
				slug:'intro',
			},
			{
				name:'Accounts',
				slug:'accounts',
			},
			{
				name:'Transactions',
				slug:'transactions',
			},
			{
				name:'Categories',
				slug:'categories',
			},
			{
				name:'Tags',
				slug:'tags',
			},
			{
				name:'Snapshots',
				slug:'snapshots',
			},
			{
				name:'Organisations',
				slug:'organisations',
			},
		]
	}
]